version: '3'

services:
  nginx_trident:
    image: 'nginx:latest'
    ports:
      - "8080:80"
    volumes:
      - ../www-data:/var/www
      - ./sites-enabled:/etc/nginx/conf.d
    container_name: nginx_trident
    tty: true
    working_dir: /var/www
    networks:
      dev:
        ipv4_address: 192.168.40.120

networks:
  dev:
    external: true