version: "3"
services:
  mariadb:
    image: "mariadb"
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "trident_test"
      MYSQL_USER: "trident_test_user"
      MYSQL_PASSWORD: "Ffk30odskm21"
    ports:
      - "3386:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      trident_test_ntw:
        ipv4_address: 192.168.40.33
networks:
  trident_test_ntw:
    external: true
