version: '3'

services:
  php7_trident:
    build:
      context: .
    volumes:
      - ../www-data:/var/www
      - ./hosts:/etc/hosts
    container_name: php7_trident
    tty: true
    working_dir: /var/www
    networks:
      trident_test_ntw:
        ipv4_address: 192.168.40.72
    environment:
      - MYSQL_DB_USER=trident_test_user
      - MYSQL_DB_PASSWORD=Ffk30odskm21
      - MYSQL_DB_HOST=mariadb
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_NAME=trident_test
      - MYSQL_VERSION=5.6
      - JWTPWD=rioejkldsn7238e6w7t

networks:
  trident_test_ntw:
    external: true