version: '3'

services:
  php7_trident:
    build:
      context: .
    volumes:
      - ../www-data:/var/www
      - ./hosts:/etc/hosts
    container_name: php7_trident
    tty: true
    working_dir: /var/www
    networks:
      trident_test_ntw:
        ipv4_address: 192.168.40.72

networks:
  trident_test_ntw:
    external: true